# Generated by Django 5.0.6 on 2024-07-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
