# Generated by Django 5.0.6 on 2024-07-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='delivery_date',
        ),
    ]
